version: '3.8'

services:
  frontend:
    build:
      context: ./www
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./www:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://api:8000
    depends_on:
      - api

  api:
    build:
      context: ./backend/app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://schedge:schedge@db:5432/schedge
    volumes:
      - ./backend/app:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - db

  db:
    image: postgres:17.5
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: schedge
      POSTGRES_PASSWORD: schedge
      POSTGRES_DB: schedge
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
