"""add availability model and related changes

Revision ID: da7a9313cfdb
Revises: 422937fb7cac
Create Date: 2025-08-16 12:09:01.843821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da7a9313cfdb'
down_revision: Union[str, Sequence[str], None] = '422937fb7cac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new columns to availabilities table
    op.add_column('availabilities', sa.Column('event_name', sa.String(), nullable=False))
    op.add_column('availabilities', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.add_column('availabilities', sa.Column('end_date', sa.DateTime(), nullable=True))
    
    # Make name column non-nullable
    op.alter_column('availabilities', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    
    # Remove old columns
    op.drop_column('availabilities', 'time_slot')
    op.drop_column('availabilities', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back old columns
    op.add_column('availabilities', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('availabilities', sa.Column('time_slot', sa.VARCHAR(), autoincrement=False, nullable=False))
    
    # Make name column nullable again
    op.alter_column('availabilities', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    
    # Remove new columns
    op.drop_column('availabilities', 'end_date')
    op.drop_column('availabilities', 'start_date')
    op.drop_column('availabilities', 'event_name')
    # ### end Alembic commands ###
